[package]
name = "mpd_dyn"
version = "0.1.0"
authors = ["neodc <noe@lal.be>"]

[dependencies]
mpd = { git = "https://github.com/neodc/rust-mpd.git", branch = "add-stickers_map" }
rand = "0.5.0-pre.0"
config = "0.8.0"
xdg = "2.1.0"
